// Client for the MAUI-API calls (contract: maui-api docs/openapi.yaml). Never throws:
// every outcome is an ApiResult, so a failing API can never break MAUI, which stays usable in
// LOCAL mode. Branches on the problem `code`, never on `title` or `detail`, as the contract asks.

export interface MauiApiCredentials {
    // Full API base, `/api/v1` included (see toApiBaseUrl() in ConfigurationString.ts).
    baseUrl: string;
    key: string;
    token: string;
    // See MachineFingerprint.ts.
    fingerprint: string;
}

export interface MauiApiClientOptions {
    fetchImpl?: typeof fetch;
    timeoutMs?: number;
}

export interface PingResult {
    client: {key: string; name: string};
    machine: {boundAt: string; newlyBound: boolean};
    serverTime: string;
}

export interface StartupReport {
    mameVersion: string;
    mauiVersion: string;
    os: 'linux' | 'darwin' | 'win32';
    osVersion: string;
    // Human-readable OS name, sent only when known (see OsName.ts).
    osName?: string;
    clientDatetime: string;
}

export interface StartupResult {
    id: string;
    receivedAt: string;
}

export interface RepositoryInfo {
    // Base URL of the starting-pack repository, null when this server has none.
    url: string | null;
}

// Players (maui-api D48): only the initials and the visibility ever reach the API.
export type OnlinePlayerStatus = 'active' | 'disabled' | 'locked';

export interface OnlinePlayer {
    // UUID, the only id the API knows the player by.
    id: string;
    pseudo3: string;
    isPublic: boolean;
    status: OnlinePlayerStatus;
    // Created on this cabinet: the only one that may issue a new PIN (maui-api D54).
    isOrigin: boolean;
    // SHA-256 of the avatar MAUI-API has (maui-api D53), null without one.
    avatar: string | null;
}

export type PlayerAvailability = 'free' | 'taken' | 'disabled';

export interface CreatedPlayer {
    player: OnlinePlayer;
    // Shown once to the player, never stored.
    pin: string;
}

// Scores (maui-api D50): only personal bests are stored, one outcome per score.
export interface ScoreSubmission {
    // UUID generated by the cabinet: the idempotency key of resends.
    id: string;
    playerId: string;
    romname: string;
    table?: string;
    score: number;
    rankOnCabinet?: number | null;
    // ISO 8601, the cabinet's clock.
    achievedAt: string;
    startupId?: string | null;
    // Set when the game wrote no name and the player was picked on the cabinet (maui-api D61).
    attribution?: 'declared';
}

export type ScoreStatus = 'accepted' | 'not_improved' | 'rejected';

export interface ScoreResult {
    id: string;
    status: ScoreStatus;
    // With `rejected` only: player_not_found, player_disabled, id_conflict...
    code?: string;
    // The player's best on the game and table, unless rejected.
    best?: number | null;
}

// Shared leaderboards (maui-api D52): the best visible score of each player, top 9.
export interface LeaderboardEntry {
    rank: number;
    playerId: string;
    pseudo3: string;
    // SHA-256 of the player's avatar (maui-api D53), null without one.
    avatar: string | null;
    score: number;
    achievedAt: string;
    cabinet: string;
}

export interface Leaderboard {
    romname: string;
    table: string;
    entries: LeaderboardEntry[];
}

// A conditional GET: `notModified` when the ETag sent still matches.
export type Conditional<T> = {notModified: true} | {notModified: false; etag: string | null; value: T};

export type ApiResult<T> =
    | {kind: 'ok'; value: T}
    // Definitive: retrying with the same credentials gives the same answer. `attemptsLeft` comes
    // with `pin_invalid` only.
    | {kind: 'rejected'; status: number; code: string; errors?: Record<string, string[]>; attemptsLeft?: number}
    | {kind: 'rate_limited'; retryAfterSeconds: number}
    // Transient: worth retrying at the next heartbeat.
    | {kind: 'unavailable'; reason: 'network' | 'timeout' | 'server_error' | 'invalid_response'; status?: number};

export type ApiFailure = Exclude<ApiResult<unknown>, {kind: 'ok'}>;

const DEFAULT_TIMEOUT_MS = 10_000;
const DEFAULT_RETRY_AFTER_SECONDS = 60;
const MAX_VERSION_LENGTH = 32;
const MAX_OS_VERSION_LENGTH = 64;

type Json = Record<string, unknown>;

function isObject(value: unknown): value is Json {
    return typeof value === 'object' && value !== null && !Array.isArray(value);
}

async function readJson(response: Response): Promise<unknown> {
    try {
        return await response.json();
    } catch {
        return null;
    }
}

function parseRetryAfter(header: string | null): number {
    const seconds = Number(header);
    return header !== null && Number.isInteger(seconds) && seconds >= 0 ? seconds : DEFAULT_RETRY_AFTER_SECONDS;
}

async function toFailure(response: Response): Promise<ApiResult<never>> {
    if (response.status === 429) {
        return {kind: 'rate_limited', retryAfterSeconds: parseRetryAfter(response.headers.get('Retry-After'))};
    }
    if (response.status >= 500) {
        return {kind: 'unavailable', reason: 'server_error', status: response.status};
    }
    const body = await readJson(response);
    const code = isObject(body) && typeof body.code === 'string' ? body.code : 'http_error';
    const rejected: ApiResult<never> = {kind: 'rejected', status: response.status, code};
    if (isObject(body) && Number.isInteger(body.attempts_left)) {
        return {...rejected, attemptsLeft: body.attempts_left as number};
    }
    return isObject(body) && isObject(body.errors)
        ? {...rejected, errors: body.errors as Record<string, string[]>}
        : rejected;
}

function parsePing(body: unknown): PingResult | null {
    if (!isObject(body) || !isObject(body.client) || !isObject(body.machine)) {
        return null;
    }
    const {client, machine} = body;
    if (typeof client.key !== 'string' || typeof client.name !== 'string'
        || typeof machine.bound_at !== 'string' || typeof machine.newly_bound !== 'boolean'
        || typeof body.server_time !== 'string') {
        return null;
    }
    return {
        client: {key: client.key, name: client.name},
        machine: {boundAt: machine.bound_at, newlyBound: machine.newly_bound},
        serverTime: body.server_time,
    };
}

function parseStartup(body: unknown): StartupResult | null {
    if (!isObject(body) || typeof body.id !== 'string' || typeof body.received_at !== 'string') {
        return null;
    }
    return {id: body.id, receivedAt: body.received_at};
}

function parseRepository(body: unknown): RepositoryInfo | null {
    if (!isObject(body) || !(typeof body.url === 'string' || body.url === null)) {
        return null;
    }
    return {url: body.url};
}

const PLAYER_STATUSES: readonly string[] = ['active', 'disabled', 'locked'];
const AVAILABILITIES: readonly string[] = ['free', 'taken', 'disabled'];
const PIN = /^\d{4}$/;

function parsePlayer(body: unknown): OnlinePlayer | null {
    if (!isObject(body) || typeof body.id !== 'string' || typeof body.pseudo_3 !== 'string'
        || typeof body.is_public !== 'boolean' || typeof body.status !== 'string'
        || !PLAYER_STATUSES.includes(body.status)) {
        return null;
    }
    return {
        id: body.id, pseudo3: body.pseudo_3, isPublic: body.is_public, status: body.status as OnlinePlayerStatus,
        isOrigin: body.is_origin === true,
        avatar: typeof body.avatar === 'string' ? body.avatar : null,
    };
}

function parsePlayerResponse(body: unknown): OnlinePlayer | null {
    return isObject(body) ? parsePlayer(body.player) : null;
}

function parsePlayerList(body: unknown): OnlinePlayer[] | null {
    if (!isObject(body) || !Array.isArray(body.players)) {
        return null;
    }
    const players = body.players.map(parsePlayer);
    return players.every(player => player !== null) ? players as OnlinePlayer[] : null;
}

function parseAvailability(body: unknown): PlayerAvailability | null {
    return isObject(body) && typeof body.availability === 'string' && AVAILABILITIES.includes(body.availability)
        ? body.availability as PlayerAvailability
        : null;
}

function parsePin(body: unknown): string | null {
    return isObject(body) && typeof body.pin === 'string' && PIN.test(body.pin) ? body.pin : null;
}

function parseCreatedPlayer(body: unknown): CreatedPlayer | null {
    const player = parsePlayerResponse(body);
    const pin = parsePin(body);
    return player && pin ? {player, pin} : null;
}

function parseLeaderboardEntry(body: unknown): LeaderboardEntry | null {
    if (!isObject(body) || typeof body.rank !== 'number' || !isObject(body.player) || typeof body.score !== 'number'
        || typeof body.player.id !== 'string' || typeof body.player.pseudo_3 !== 'string'
        || typeof body.achieved_at !== 'string' || typeof body.cabinet !== 'string') {
        return null;
    }
    return {
        rank: body.rank, playerId: body.player.id, pseudo3: body.player.pseudo_3,
        avatar: typeof body.player.avatar === 'string' ? body.player.avatar : null,
        score: body.score, achievedAt: body.achieved_at, cabinet: body.cabinet,
    };
}

function parseLeaderboard(body: unknown): Leaderboard | null {
    if (!isObject(body) || typeof body.romname !== 'string' || typeof body.table !== 'string' || !Array.isArray(body.entries)) {
        return null;
    }
    const entries = body.entries.map(parseLeaderboardEntry);
    return entries.every(entry => entry !== null)
        ? {romname: body.romname, table: body.table, entries: entries as LeaderboardEntry[]}
        : null;
}

function parseLeaderboards(body: unknown): Leaderboard[] | null {
    if (!isObject(body) || !Array.isArray(body.leaderboards)) {
        return null;
    }
    const leaderboards = body.leaderboards.map(parseLeaderboard);
    return leaderboards.every(leaderboard => leaderboard !== null) ? leaderboards as Leaderboard[] : null;
}

const SCORE_STATUSES: readonly string[] = ['accepted', 'not_improved', 'rejected'];

function parseScoreResult(body: unknown): ScoreResult | null {
    if (!isObject(body) || typeof body.id !== 'string' || typeof body.status !== 'string'
        || !SCORE_STATUSES.includes(body.status)) {
        return null;
    }
    return {
        id: body.id,
        status: body.status as ScoreStatus,
        ...(typeof body.code === 'string' ? {code: body.code} : {}),
        ...(typeof body.best === 'number' || body.best === null ? {best: body.best} : {}),
    };
}

function parseScoreResults(body: unknown): ScoreResult[] | null {
    if (!isObject(body) || !Array.isArray(body.results)) {
        return null;
    }
    const results = body.results.map(parseScoreResult);
    return results.every(result => result !== null) ? results as ScoreResult[] : null;
}

function isTimeout(error: unknown): boolean {
    return error instanceof Error && (error.name === 'TimeoutError' || error.name === 'AbortError');
}

export class MauiApiClient {
    private readonly fetchImpl: typeof fetch;
    private readonly timeoutMs: number;

    public constructor(private readonly credentials: MauiApiCredentials, options: MauiApiClientOptions = {}) {
        // Never the bare global stored as a property: called as `this.fetchImpl()`, the renderer's
        // browser fetch throws "Illegal invocation" (Node's does not care), seen as a network error.
        this.fetchImpl = options.fetchImpl ?? ((input, init) => fetch(input, init));
        this.timeoutMs = options.timeoutMs ?? DEFAULT_TIMEOUT_MS;
    }

    public ping(): Promise<ApiResult<PingResult>> {
        return this.call('GET', '/ping', 200, async response => parsePing(await readJson(response)));
    }

    public reportStartup(report: StartupReport): Promise<ApiResult<StartupResult>> {
        const body = {
            mame_version: report.mameVersion.slice(0, MAX_VERSION_LENGTH),
            maui_version: report.mauiVersion.slice(0, MAX_VERSION_LENGTH),
            os: report.os,
            os_version: report.osVersion.slice(0, MAX_OS_VERSION_LENGTH),
            ...(report.osName ? {os_name: report.osName.slice(0, MAX_OS_VERSION_LENGTH)} : {}),
            client_datetime: report.clientDatetime,
        };
        return this.call('POST', '/startups', 201, async response => parseStartup(await readJson(response)), body);
    }

    public heartbeat(): Promise<ApiResult<void>> {
        return this.call('POST', '/heartbeat', 204, async () => undefined);
    }

    public repository(): Promise<ApiResult<RepositoryInfo>> {
        return this.call('GET', '/repository', 200, async response => parseRepository(await readJson(response)));
    }

    public listPlayers(): Promise<ApiResult<OnlinePlayer[]>> {
        return this.call('GET', '/players', 200, async response => parsePlayerList(await readJson(response)));
    }

    public playerAvailability(pseudo3: string): Promise<ApiResult<PlayerAvailability>> {
        return this.call(
            'GET', `/players/availability?pseudo_3=${encodeURIComponent(pseudo3)}`, 200,
            async response => parseAvailability(await readJson(response)),
        );
    }

    public createPlayer(pseudo3: string, isPublic: boolean): Promise<ApiResult<CreatedPlayer>> {
        return this.call(
            'POST', '/players', 201, async response => parseCreatedPlayer(await readJson(response)),
            {pseudo_3: pseudo3, is_public: isPublic},
        );
    }

    public linkPlayer(pseudo3: string, pin: string): Promise<ApiResult<OnlinePlayer>> {
        return this.call(
            'POST', '/players/link', 200, async response => parsePlayerResponse(await readJson(response)),
            {pseudo_3: pseudo3, pin},
        );
    }

    public updatePlayer(id: string, isPublic: boolean): Promise<ApiResult<OnlinePlayer>> {
        return this.call(
            'PATCH', `/players/${encodeURIComponent(id)}`, 200, async response => parsePlayerResponse(await readJson(response)),
            {is_public: isPublic},
        );
    }

    public regeneratePin(id: string): Promise<ApiResult<string>> {
        return this.call('POST', `/players/${encodeURIComponent(id)}/pin`, 200, async response => parsePin(await readJson(response)));
    }

    public unlinkPlayer(id: string): Promise<ApiResult<void>> {
        return this.call('DELETE', `/players/${encodeURIComponent(id)}/link`, 204, async () => undefined);
    }

    /** At most 100 scores (maui-api D50); one result per score, in the order sent. */
    public postScores(scores: ScoreSubmission[]): Promise<ApiResult<ScoreResult[]>> {
        return this.call(
            'POST', '/scores', 200, async response => parseScoreResults(await readJson(response)),
            {scores: scores.map(score => ({
                id: score.id,
                player_id: score.playerId,
                romname: score.romname,
                ...(score.table ? {table: score.table} : {}),
                score: score.score,
                rank_on_cabinet: score.rankOnCabinet ?? null,
                achieved_at: score.achievedAt,
                startup_id: score.startupId ?? null,
                ...(score.attribution ? {attribution: score.attribution} : {}),
            }))},
        );
    }

    /** At most 100 games (maui-api D52); `etag` from the last answer for the same games. */
    public async getLeaderboards(romnames: string[], etag: string | null = null): Promise<ApiResult<Conditional<Leaderboard[]>>> {
        const response = await this.send(
            'GET', `/leaderboards?romnames=${romnames.map(encodeURIComponent).join(',')}`,
            etag ? {'If-None-Match': etag} : {},
        );
        if (!(response instanceof Response)) {
            return response;
        }
        if (response.status === 304) {
            return {kind: 'ok', value: {notModified: true}};
        }
        if (!response.ok) {
            return toFailure(response);
        }
        const leaderboards = response.status === 200 ? parseLeaderboards(await readJson(response)) : null;
        return leaderboards === null
            ? {kind: 'unavailable', reason: 'invalid_response', status: response.status}
            : {kind: 'ok', value: {notModified: false, etag: response.headers.get('ETag'), value: leaderboards}};
    }

    /** The PNG of a public player (maui-api D53). */
    public async getAvatar(playerId: string): Promise<ApiResult<Uint8Array>> {
        const response = await this.send('GET', `/players/${encodeURIComponent(playerId)}/avatar`, {Accept: 'image/png'});
        if (!(response instanceof Response)) {
            return response;
        }
        if (!response.ok) {
            return toFailure(response);
        }
        return {kind: 'ok', value: new Uint8Array(await response.arrayBuffer())};
    }

    /** Sends the PNG of a player of this cabinet; answers its hash as MAUI-API stored it. */
    public uploadAvatar(playerId: string, png: Uint8Array): Promise<ApiResult<string>> {
        const form = new FormData();
        form.append('avatar', new Blob([new Uint8Array(png)], {type: 'image/png'}), 'avatar.png');
        return this.call(
            'POST', `/players/${encodeURIComponent(playerId)}/avatar`, 200,
            async response => {
                const body = await readJson(response);
                return isObject(body) && typeof body.avatar === 'string' ? body.avatar : null;
            },
            form,
        );
    }

    private headers(hasBody: boolean): Record<string, string> {
        const headers: Record<string, string> = {
            'X-Maui-Key': this.credentials.key,
            'Authorization': `Bearer ${this.credentials.token}`,
            'X-Maui-Machine': this.credentials.fingerprint,
            'Accept': 'application/json',
        };
        return hasBody ? {...headers, 'Content-Type': 'application/json'} : headers;
    }

    private async call<T>(
        method: 'GET' | 'POST' | 'PATCH' | 'DELETE',
        path: string,
        expectedStatus: number,
        parse: (response: Response) => Promise<T | null>,
        body?: Json | FormData,
    ): Promise<ApiResult<T>> {
        const response = await this.send(method, path, {}, body);
        if (!(response instanceof Response)) {
            return response;
        }
        if (!response.ok) {
            return toFailure(response);
        }
        const value = response.status === expectedStatus ? await parse(response) : null;
        return value === null
            ? {kind: 'unavailable', reason: 'invalid_response', status: response.status}
            : {kind: 'ok', value};
    }

    /** The response, whatever its status, or why there is none. */
    private async send(
        method: 'GET' | 'POST' | 'PATCH' | 'DELETE', path: string, extraHeaders: Record<string, string>, body?: Json | FormData,
    ): Promise<Response | ApiResult<never>> {
        const isForm = body instanceof FormData;
        try {
            return await this.fetchImpl(this.credentials.baseUrl.replace(/\/+$/, '') + path, {
                method,
                // multipart: fetch sets the Content-Type, with its boundary.
                headers: {...this.headers(body !== undefined && !isForm), ...extraHeaders},
                body: body === undefined ? undefined : isForm ? body : JSON.stringify(body),
                // The API never redirects: following one could hand the token to another host.
                redirect: 'error',
                signal: AbortSignal.timeout(this.timeoutMs),
            });
        } catch (error) {
            return {kind: 'unavailable', reason: isTimeout(error) ? 'timeout' : 'network'};
        }
    }
}
